apiVersion: v1
kind: Service
metadata:
  name: simple-file-upload
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: simple-file-upload
